# Generated by Django 4.2.5 on 2023-10-30 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('temp', models.FloatField()),
                ('sound', models.FloatField()),
                ('time_stamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'TESTtb',
                'managed': False,
            },
        ),
    ]
